let example_text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas lacinia et leo non semper. Nam dictum massa purus, tristique rutrum urna fringilla id. Vivamus quis elit a odio aliquet commodo. Praesent finibus enim id ultricies ultricies. Nullam viverra volutpat mi non blandit. Aliquam sit amet arcu vel ligula blandit volutpat at ut orci. Proin in iaculis ipsum, semper tincidunt urna. Sed sed erat iaculis, cursus sem at, rhoncus tellus.\nInterdum et malesuada fames ac ante ipsum primis in faucibus. Donec finibus aliquet venenatis. Aliquam erat volutpat. Vivamus posuere dolor ut tortor congue accumsan. Etiam finibus feugiat diam, vel dictum arcu blandit vitae. Morbi finibus tortor ut dui aliquet tristique in quis quam. Aenean a magna accumsan, ornare leo at, tempus felis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus vulputate scelerisque neque ut aliquet. Integer aliquam velit ut cursus luctus. Curabitur ultricies lacinia quam sit amet porttitor. Cras ante elit, ullamcorper eget fermentum sed, blandit sit amet quam. In dictum in ante sit amet vehicula. Sed nibh magna, vehicula ut vulputate id, condimentum sit amet justo. Fusce vehicula nisl justo, eget lobortis justo eleifend in.\nPraesent semper nisl sed nisi hendrerit interdum. Donec libero sem, molestie sit amet convallis quis, dignissim ac ex. Aliquam semper urna eget nisl luctus tempus. Nunc consequat at libero a tempor. Integer ac odio id enim ornare eleifend. Phasellus velit eros, malesuada ac venenatis in, molestie at ipsum. Quisque vestibulum dapibus tempus.\nDuis velit nisi, accumsan a iaculis vel, dapibus at sem. Vivamus sem velit, pretium et metus ac, pharetra ultrices magna. Curabitur id nisl a augue tempor blandit hendrerit sed metus. In maximus leo non viverra venenatis. Vestibulum consectetur ullamcorper nulla ut dignissim. Sed pellentesque, odio at vulputate consectetur, leo nulla tincidunt dui, in suscipit dui arcu eu neque. Nam ornare, massa ut rutrum aliquet, sapien enim viverra tortor, ac ullamcorper nisl mauris nec purus. In hac habitasse platea dictumst. Nullam tincidunt ligula eu nulla porttitor cursus. Nam at hendrerit erat. Mauris aliquam et ipsum vitae porta.\nSuspendisse porta euismod lorem id semper. Sed et est lectus. Fusce sodales congue ultricies. In ac sem elementum dolor porta varius. Phasellus nec elit a ligula condimentum rhoncus condimentum ac erat. Duis porta a nibh eu maximus. Aenean scelerisque, nulla eu tempor feugiat, odio erat cursus leo, a pretium sem purus suscipit dui. Curabitur lobortis urna sed sapien bibendum, ut malesuada est placerat. Proin eget massa eu risus imperdiet porta vitae vel felis. Nunc fermentum neque sed ultrices porttitor. Praesent suscipit pulvinar nisi nec egestas. Nullam porta eros accumsan mi mollis tempor. Duis eleifend dictum faucibus."

var ContentSectionArray = [].slice.call(document.getElementsByTagName("P"));

ContentSectionArray.forEach(element => {
    element.innerText = example_text;
});

//TODO: Añadir "example_text" a todos los P del documento
//TODO: Comprobar por qué falla al cargar el script vue.min.js

console.log("Main.js cargado!");